### ISSUE TITLE
ttl is broken

### ISSUE THREAD

**Issue by lbenedix** [eruvanos/dynafile#1]
Trying to get a deleted item is resulting in big explosions when using the ttl-feature.

```
db = Dynafile(path=f"test", pk_attribute="PK", sk_attribute="SK", ttl_attribute="ttl")
db.put_item(item={"PK":"pk", "SK": "sk", "ttl": time.time()+1})
db.get_item(key={"PK":"pk", "SK": "sk"})
db.get_item(key={"PK":"pk", "SK": "sk"})
Traceback (most recent call last):
  File "/Users/vwgb44b/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/221.5080.212/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/Users/vwgb44b/.local/share/virtualenvs/lvz_feed-5-bQVj0c/lib/python3.9/site-packages/dynafile/__init__.py", line 214, in get_item
    if self._ttl_should_delete(item):
  File "/Users/vwgb44b/.local/share/virtualenvs/lvz_feed-5-bQVj0c/lib/python3.9/site-packages/dynafile/__init__.py", line 271, in _ttl_should_delete
    ttl = item.get(self._ttl_attribute)
AttributeError: 'NoneType' object has no attribute 'get'
```

without ttl_attribute set it works like expected:
```
db = Dynafile(path=f"test", pk_attribute="PK", sk_attribute="SK")
db.get_item(key={"PK":"pk", "SK": "sk"})
db.get_item(key={"PK":"pk", "SK": "sk"})
```

**Comment by lbenedix** [comment]
Same happens when there is no item with a given key in the first place.
```
db = Dynafile(path=f"test", pk_attribute="PK", sk_attribute="SK", ttl_attribute="ttl")
db.get_item(key={"PK":"pk", "SK": "sk"})
Traceback (most recent call last):
  File "/Users/vwgb44b/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/221.5080.212/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/Users/vwgb44b/.local/share/virtualenvs/lvz_feed-5-bQVj0c/lib/python3.9/site-packages/dynafile/__init__.py", line 214, in get_item
    if self._ttl_should_delete(item):
  File "/Users/vwgb44b/.local/share/virtualenvs/lvz_feed-5-bQVj0c/lib/python3.9/site-packages/dynafile/__init__.py", line 271, in _ttl_should_delete
    ttl = item.get(self._ttl_attribute)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by lbenedix** [comment]
should be fixed by https://github.com/eruvanos/dynafile/pull/2
